---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: gitlab-server
  name: gitlab-data
  namespace: walton-sso
spec:
  storageClassName: rook-cephfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
